Adds Base64 Data URI support
ClickPop/friendlyfaces-api pull request #39
Opened 2021-06-03 20:38 UTC by seanmetzgar

2021-06-03 20:39 UTC, seanmetzgar commented
Give this a whirl and make sure it's all working... I may have messed up the docs, not sure how to test that.

2021-06-03 20:40 UTC, seanmetzgar commented
accept: text/plain : ?base64=true (svg data uri)
accept: text/plain : ?base64=true&format=svg (svg data uri)
accept: text/plain : ?base64=true&format=png (png data uri... it's BIG)

2021-06-04 23:57 UTC, GV14982 requested changes

2021-06-04 23:57 UTC, GV14982 commented on routes/faces/faces.go
> +				returnString = "data:image/svg;base64," + b64.StdEncoding.EncodeToString([]byte(graphic))
Can you switch that prefix to `data:image:svg+xml;base64`?

I remember it causing a weird bug, but I don't remember the specifics.

2021-06-04 23:58 UTC, GV14982 commented
I'll test this out later tonight or tomorrow.

2021-06-05 00:05 UTC, seanmetzgar commented
I’m making some minor changes anyway… no worries

Sean Metzgar

Sent via Superhuman iOS ( ***@***.*** )

On Fri, Jun 4 2021 at 19:59, Graham Vasquez < ***@***.*** > wrote:

> 
> 
> 
> 
> 
> 
> 
> I'll test this out later tonight or tomorrow.
> 
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub (
> https://github.com/ClickPop/friendlyfaces-api/pull/39#issuecomment-855141726
> ) , or unsubscribe (
> https://github.com/notifications/unsubscribe-auth/AABMRGALLHYXWLLACWT7HGDTRFSFBANCNFSM46BPIHMQ
> ).
> 
> 
>

2021-06-05 05:33 UTC, seanmetzgar commented on routes/faces/faces.go
> +				returnString = "data:image/svg;base64," + b64.StdEncoding.EncodeToString([]byte(graphic))
good to go now 😸

2021-06-05 05:37 UTC, seanmetzgar commented
cleaned this up a bit... just this now
accept: text/plain : ?base64=svg (svg data uri)
accept: text/plain : ?base64=png (png data uri... it's BIG)

2021-06-05 16:06 UTC, GV14982 approved these changes
Tested it out, nice job 👍🏻

2021-06-05 16:06 UTC, merged